### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by r3dnasa** [hbivnm/Venom-Crosshairs#2]
currently it is impossible to compile this when downloading the source code straight from github. it throws up errors in vscode studio about resources.resx. it seems like its referencing missing files in a folder called ..\bin\Debug\resources\
![image](https://github.com/hbivnm/Venom-Crosshairs/assets/82971054/63fa155f-bc0d-47c6-a437-fa0491bec904)

it also references these missing dependencies tho that might just be a me issue
![image](https://github.com/hbivnm/Venom-Crosshairs/assets/82971054/90375234-9a21-48d5-976f-4ae48e816711)

**Comment by hbivnm** [comment]
Hey @r3dnasa, sorry for the very delayed response. This should now be resolved, please see [b5d0dda](https://github.com/hbivnm/Venom-Crosshairs/commit/b5d0dda75bbd5b2699a3e43ba9c085c6bb1bf8cc#diff-18193a5ba16a549dee3f4b3d98aa37ed77c937636df0f9d7cc98ac7259444571).

**Comment by r3dnasa** [comment]
It's okay, thanks for fixing it man
