### ISSUE TITLE
sStuck on Copyign mAterials

### ISSUE THREAD

**Issue by KaiDaSamuraii** [hbivnm/Venom-Crosshairs#3]
![image_2024-02-08_012717204](https://github.com/hbivnm/Venom-Crosshairs/assets/108827183/c59370dd-2e6b-4c4b-824e-8e8a085a91b9)
trying to import more crosshairs but stuck on copying materials

**Comment by hbivnm** [comment]
Yo, need more info to be able to help out.

- Where did you extract the release (folder named VenomCrosshairs)?
- How did you import `yzremake2`?

**Comment by hbivnm** [comment]
10 days without additional response, closing.
