### ISSUE TITLE
Invalid TF2 path error due to new 64bit update

### ISSUE THREAD

**Issue by TechnoSL** [hbivnm/Venom-Crosshairs#5]
title explains it, the program now dies due to the new tf2 executable being named `tf_win64.exe` as of the [April 18th, 2024 update](https://www.teamfortress.com/post.php?id=220436)

this is probably a small fix by changing [one line of code](https://github.com/hbivnm/Venom-Crosshairs/blob/master/VenomCrosshairs/FormMain.cs#L1607), but i'm reporting it since i have no clue on how to build this project

![image](https://github.com/hbivnm/Venom-Crosshairs/assets/41777800/ef3b3763-5b1a-473d-a001-9c9975ef69b9)
![image](https://github.com/hbivnm/Venom-Crosshairs/assets/41777800/2e409bd2-31b9-45b4-bb98-a6c346ce5c07)

**Comment by hbivnm** [comment]
Hi and thank you!

This is now fixed along with a smaller release: [b14.1](https://github.com/hbivnm/Venom-Crosshairs/releases/tag/beta14)
