### ISSUE TITLE
coping materials

### ISSUE THREAD

**Issue by Nahga0710** [hbivnm/Venom-Crosshairs#6]
![1212](https://github.com/hbivnm/Venom-Crosshairs/assets/167635898/07b906c4-c2ff-40cd-a9ae-a99c23c6d64c)

hello, my cilent seems not working, it keep coping materials then stuck here , i dont know how to solve this isse

**Comment by hbivnm** [comment]
Hi @Nahga0710 , where did you extract the Venom Crosshairs release?

**Comment by Nahga0710** [comment]
here

**Comment by hbivnm** [comment]
No, not downloaded. What directory did you extract it to (on your pc)?

**Comment by Nahga0710** [comment]
oh wait i havent extract, i just open that exe with zip, sorry my fault

**Comment by hbivnm** [comment]
Make sure you follow the correct installation process found in the README [here](https://github.com/hbivnm/Venom-Crosshairs?tab=readme-ov-file#tutorial--installation). Closing this issue.
