### ISSUE TITLE
All class option on config read

### ISSUE THREAD

**Issue by cazaman11** [hbivnm/Venom-Crosshairs#7]
More of a feature than a bug imo. When first opening the app, you're unable to modify the weapon and crosshair dropdowns and required to select a class. however if you click the read config button it will make those dropdowns selectable allowing you to apply to all classes if you dont select a class.

I think it'd be best to keep this feature but have it more accessable with either a clearing the class option or an all class option.

**Comment by hbivnm** [comment]
I'm not sure what you mean with having it _more accessible_, you are able to apply a single crosshair to all classes by:

1. Going through the normal UI flow of choosing a **class** -> **weapon** -> **crosshair** -> check relevant checkboxes
![image](https://github.com/hbivnm/Venom-Crosshairs/assets/47778018/0b652750-fd4f-4f58-b715-938dd9d1cf75)

2. Different, but slightly unintended, way by **reading config** -> select a **crosshair** -> check relevant checkboxes
![VenomCrosshairs_VsZ1W7cWEb](https://github.com/hbivnm/Venom-Crosshairs/assets/47778018/97633ae4-db28-427f-bf2a-08d99e53c85a)

The dropdowns and checkboxes are explicitly grayed out to have some form of flow to not confuse the user with a boatload of dropdowns, checkboxes and buttons (hence settings and console are hidden by default).

I'd be more than happy to consider other alternatives if you'd like to explain step-by-step and/or show with examples of having more options to apply things to all classes! :)

**Comment by hbivnm** [comment]
Issue inactive for +100 days, closing. 

Again, I appreciate all the feedback.
